# Generated by Django 2.2.28 on 2023-06-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
